### ISSUE TITLE
Add section on past, current and upcoming courses

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/kottans.github.io#116]
List fields:
* Course/Tech Stack name
* Hosting city
* Course lead (profile link)
* Course start
* Course end
* course type (online/offline)
* link to youtube playlist
* ?

Collection of info sources:
* https://github.com/kottans/kottans-ongoing-projects/issues
* https://github.com/kottans/kottans-ongoing-projects/issues?q=is%3Aissue+is%3Aclosed

**Comment by nazmariam** [comment]
[https://docs.google.com/document/d/1voialQrW1nlYA70nUl3I_-KBCzhxuKlP4xdPRNvfE1w/edit?ts=5cab9c18#heading=h.luc09p73yswl](link for courses section in landing page)

**Comment by nazmariam** [comment]
[link for courses section in landing page](https://docs.google.com/document/d/1voialQrW1nlYA70nUl3I_-KBCzhxuKlP4xdPRNvfE1w/edit?ts=5cab9c18#heading=h.luc09p73yswl)
