### ISSUE TITLE
Bug: Missing coaches images

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/kottans.github.io#119]
At https://kottans.org/#team many images are missing from the past years

**Comment by suchov** [comment]
@OleksiyRudenko do you mean something like Eugene Coshevoy form 2013-2014 ?

**Comment by sudodoki** [comment]
Eugene doesn’t have any images in net and explicitly asked not to have one,
but yeah, there are some broken images for some coaches who have
full_img_url that isn’t valid anymore

**Comment by suchov** [comment]
@OleksiyRudenko couple persons left but I made several commits

**Comment by OleksiyRudenko** [comment]
@suchov I meant some images are broken and not available anymore at source. Thanks @sudodoki for clarification.
People that left is OK since they were in on the time being, IMO
