### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans.github.io#127]
We need to add the FAQ section on site. Let's collect list of questions and answers.

**When next course will start?**

We don't know :) Our courses are irregular and when we decide to launch one - we will an announcement on our twitter account and telegram channel Radio Kottans.
But don't get upset, because all programs are available on GitHub and you can complete tasks with other students. We call this format P2P education.

**From what courses made of?**

Usually, we separating our course on two parts - online and offline. To get to the offline part, one should complete an online part.
The online part is a list of tasks - video-lectures, code tasks, etc.
The offline part - set of meetings, workshops, etc.

**How I can register on course?**

In general, we do not require registration, assigning or any other bureaucracy. You can just dive into the program of course by starting to complete tasks. Yes. It is so simple.

I believe we need to clarify part with p2p, but I am not sure how.
Any ideas?

Looking for your opinion 
@Croftyland 
@OleksiyRudenko 
@suchov 
@AMashoshyna

**Comment by Croftyland** [comment]
1. How it’s possible to join your courses?
2. Do you record your lessons if I missed one?
3. I’m lack of knowledge but I feel so motivated for hard work. Have I any chance to join you?
4. How do we communicate with our mentors?
5. Can I ask questions which are not related to our studies?(for instance my work tasks or library framework)

**Comment by sudodoki** [comment]
When will Kottans course happen in %cityname%
When will Kottans course in %technology% happen
What do you get out of it? Are you recruiters?

**Comment by zonzujiro** [comment]
Example of design

![image](https://user-images.githubusercontent.com/2997359/70332624-b3b74380-184a-11ea-8e25-5fdfc89151f6.png)

**Comment by zonzujiro** [comment]
Ok, I believe thats enough for now.

Thank you!
