### ISSUE TITLE
List of improvements

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans.github.io#133]
- CTA in platform section
- links to telegram channels - radio and public
- active and inactive courses, date of start of the next course
- add minigame to the second screen

**Comment by suchov** [comment]
as an idea - maybe we can split this in separate the list in small issues

**Comment by zonzujiro** [comment]
Fill free to do this as you like :)

**Comment by OleksiyRudenko** [comment]
Item 2 dubbed in #140

**Comment by zonzujiro** [comment]
Updating list for designer:

1. CTA in platform section:
 - button or smth to send and email to kottans or contact with me in telegram
2. slides with courses:
- sign if course active or p2p right now
- date of start of the next course - maybe something similar to counter in Input section

3. section with a current youtube translation
- will contain embed youtube player:
![image](https://user-images.githubusercontent.com/2997359/72807519-41ff5180-3c60-11ea-99b5-e902d390b27b.png)
Size of player can be any

4. section with info about Radio Kottans and YouTube Channel
- and here I don't have an ideas at all
