### ISSUE TITLE
Bug: It is unable to scroll mentors list using only mouse

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans.github.io#136]
It looks like, that we should show the scrollbar, after all.
Or replace scroll logic with something else, like read more button

**Comment by suchov** [comment]
I think also we can show com errors like ">>"  to move up/down backward forward as an option?

**Comment by suchov** [comment]
https://cdn2.iconfinder.com/data/icons/arrows-set-8/100/expand_arrow-512.png

**Comment by suchov** [comment]
https://cdn2.iconfinder.com/data/icons/arrows-set-8/100/back-512.png

**Comment by suchov** [comment]
or something like that

**Comment by zonzujiro** [comment]
Errors? What do you mean? Not sure what you mean :)

Your proposal is to add arrows and make scrolling vertical rather horizontal?

**Comment by suchov** [comment]
sorry - arrows, yes.
make them clickable to scroll if someone is interested :)

**Comment by zonzujiro** [comment]
Had similar idea.
We should have arrows in designs

**Comment by zonzujiro** [comment]
I have reconsidered my opinion. I believe we can replace it with vertical scroll and hide scrollbar.
@suchov WDYT?

**Comment by suchov** [comment]
I don't mind, both options work for me. Considering that we don't have a lot of time I'm voting for things that will be easier to implement.
