### ISSUE TITLE
Add links to Kottans telegram chats

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/kottans.github.io#140]
How about adding links to our tg chats?

1. From socials bar (both top and bottom) to https://t.me/kottans (with standard tg icon) and https://t.me/radio_kottans (with some special icon)
![image](https://user-images.githubusercontent.com/8686631/71920756-2429eb00-3190-11ea-8567-65422f9ab908.png)
![image](https://user-images.githubusercontent.com/8686631/71921019-ae724f00-3190-11ea-801b-9ce45d66bb43.png)

2. In https://kottans.org/#courses section to https://t.me/joinchat/DmX0JBHVkEhV1us2HdMmpA (FE chat) and https://t.me/joinchat/Dqrdixe1c2K9bXUFBzNWtg (BE chat) respectively
![image](https://user-images.githubusercontent.com/8686631/71921063-c3e77900-3190-11ea-9013-b8d96f07ed33.png)

3. `mailto:` often doesn't work for web-based mailers without tambourine. Perhaps we need different contact method for this
![image](https://user-images.githubusercontent.com/8686631/71921171-0315ca00-3191-11ea-93c4-9d7220f3a3e5.png)

**Comment by zonzujiro** [comment]
Please, can you be more specific in the third item?

**Comment by OleksiyRudenko** [comment]
> Also, I believe it will be better to move the third item out of scope of this issue, because it is related only to telegram, AFAIU. Or your idea is to use telegram instead of email?

Unless anything better comes to our mind, yes, replace with a tg. However, link to some public chat is not the best option... No good idea at the moment.

**Comment by zonzujiro** [comment]
Dunno, I am not sure about public chat also. Not everyone have telegram.
