### ISSUE TITLE
Add Open Graph and Twitter meta tags and media for better web-site preview in socials

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/kottans.github.io#142]
Web-site preview in e.g. fb looks as follows:
![image](https://user-images.githubusercontent.com/8686631/72022366-e654c180-3278-11ea-8135-82f56d431976.png)

Solution:
Add [fb/og](https://developers.facebook.com/docs/sharing/webmasters/) and [twitter summary card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary)

**Comment by A-Ostrovnyy** [comment]
For image, we will use just kottans logo, or it must be some special image?

**Comment by zonzujiro** [comment]
@A-Ostrovnyy lets use logo with white background. Thank you.

Also, I completely forgot, that @nazmariam made a text. Sorry about that :D

**Comment by A-Ostrovnyy** [comment]
@zonzujiro send me the text, I'll try to close this issue this evening. Thanks.

**Comment by zonzujiro** [comment]
The volunteer community of people who love to code and help each other. We have a lot of experience in conducting tech courses, meetups, and conferences as well. Come join us! Knowledge must be shared

**Comment by A-Ostrovnyy** [comment]
Can you provide me with Facebook admin ids?

**Comment by zonzujiro** [comment]
What ids? What you mean? id of a user?

**Comment by A-Ostrovnyy** [comment]
> What ids? What you mean? id of a user?

Yes see example in [PR](https://github.com/kottans/kottans.github.io/pull/145) example from input conference.

**Comment by zonzujiro** [comment]
100003342204377, 1744734572, 100000443393783
