### ISSUE TITLE
Bug: unable to scroll navigation menu on mobile

### ISSUE THREAD

**Issue by gorodiskiy** [kottans/kottans.github.io#143]
![Screenshot_8](https://user-images.githubusercontent.com/22916647/72067089-b8a86080-32ea-11ea-8240-e39fcc5ed744.jpg)
![photo_2020-01-09_14-16-12](https://user-images.githubusercontent.com/22916647/72067093-b8a86080-32ea-11ea-9900-b99097fc43a2.jpg)
![photo_2020-01-09_14-16-12 (2)](https://user-images.githubusercontent.com/22916647/72067097-b8a86080-32ea-11ea-966d-29f3d122774e.jpg)

**Comment by zonzujiro** [comment]
Regarding first screen - pls, tell your screen resolution

**Comment by gorodiskiy** [comment]
> Regarding first screen - pls, tell your screen resolution

1366 px
