### ISSUE TITLE
RFC: As a contributor I would like to see my contribution even if it's not visible in git metrics

### ISSUE THREAD

**Issue by yevhenorlov** [kottans/kottans.github.io#161]
It would be nice to make people who help the site visible, even if they don't write code.
Saw this thing in multiple OSS repos, I think it would be a great addition https://allcontributors.org/

TODO:

- [ ] Add historical contributors to the codebase (PR: https://github.com/kottans/kottans.github.io/pull/160)
- [ ] Add non-code contributors by hand
- [ ] Use all-contributors bot for future contributions

**Comment by zonzujiro** [comment]
What do you under mean "helped with the site, but didn't write the code"?

Some time ago we had contributors who have added themself into the old version of the site as a lector. So they will be in the git history. Not sure can we call this "contributing to the website". Also, not sure that such contributing worth mentioning in `README` in this repo.

Gathering such data for Kottans in general maybe can be good idea, tho. As an example, we mentioned lectors and mentors, but we have volunteers from alumni, as an example. They are not mentioned anywhere. Can we collect such a list and place it, saying, in some `*.md` for our Docusaur? Right now @Croftyland working on it. Pls see https://github.com/kottans/kottans-ongoing-projects/issues/40

**Comment by yevhenorlov** [comment]
> What do you under mean "helped with the site, but didn't write the code"?

Designers, bug-reporters, people who contributed to the discussion. The point of `all-contributors` tool is to do just that, however it usually needs to be triggered manually (via CLI or Github Bot) by maintainer to recognize such contributions.
It might be that `all-contributors` tool is not the best solution here (if you don't want to mix contributions to different versions of the site). Or we could add only contributors to the current version of the site.

**Comment by zonzujiro** [comment]
@yevhenorlov it looks like, that `all-contributors` is a "tool to go" for libraries with one repo. In our reality, we will add only people who contributed to this project.

Probably we should consider mentioning more contributors, in general? Not only into one repo of our organization?

At least, we have `chernivtsi-frontend-*`, mentors from p2p, alumni and volunteers, etc.

**Comment by Croftyland** [comment]
@yevhenorlov would you mind to write down all those people in Endorsements?
