### ISSUE TITLE
RFC: Change project structure

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans.github.io#163]
Right now our project have "flat" structure. All JS in one folder, all templates in second, all styles in third. While this can be good for small projects, our site already right now has a lot of entities and in a future will have more.

What do you think if we will change structure to modular? Like:

```
src
-- menu
---- menu.js
---- menu.scss
---- menu.html

-- core
---- core.js
---- core.scss
---- core.html
```

I am sure, that you saw this structure here and there and familiar with it.

Looking for your opinion @yevhenorlov @A-Ostrovnyy

**Comment by yevhenorlov** [comment]
I would be in favor of keeping the structure relatively flat (there's a valid reasoning here https://twitter.com/dan_abramov/status/1145354949871767552), however, I agree that organizing modules by business logic makes more sense that organizing them by file extension.
What changes together, lives together, that sort of thing (same goes for tests, if we decide to add them later).
