### ISSUE TITLE
Possibly, a bug: white stripe above footer

### ISSUE THREAD

**Issue by sudodoki** [kottans/kottans.github.io#169]
Might be as intended but looks slightly off, so reporting this
On resolution with width below 768px a white stripe is shown between partners and footer, see screenshot
![image](https://user-images.githubusercontent.com/1506905/78660432-bb105b80-78d5-11ea-93f2-6300466d7c96.png)
Linux, Chrome 80.0.3987.149

**Comment by zonzujiro** [comment]
New site in progress - https://github.com/kottans/kottans.github.io/pull/167

So not relevant for now.
