### ISSUE TITLE
Bug: above 1100px, an extra horizontal scroll + different section sizing

### ISSUE THREAD

**Issue by sudodoki** [kottans/kottans.github.io#170]
On screens with width above 1100 (and below 1280 at least)
an extra horizontal scroll is present (and you can scroll contact us off the screen)
![image](https://user-images.githubusercontent.com/1506905/78660843-789b4e80-78d6-11ea-9559-f2634e1458cc.png)
and all sections but a few are having empty space to the right and only team seem to be taking 100% of the width
Linux, Chrome 80.0.3987.149

**Comment by zonzujiro** [comment]
New site in progress - https://github.com/kottans/kottans.github.io/pull/167

So not relevant for now.
