### ISSUE TITLE
Add note on courses NOT being online

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#21]
Currently there're a lot of questions whether courses will be held online or in a classroom. Should fix that by adding a note/

**Comment by sudodoki** [comment]
>self-assigned this on Sep 22, 2014

@programulya how's it going? :smile: Did you come up with visual idea? Could take this off your hands.

**Comment by programulya** [comment]
Excuse me guys :woman: I completely forgot about that

**Comment by mayosh** [comment]
@programulya It's time to remind, darling. ;)

**Comment by suchov** [comment]
one more time to remind )))

**Comment by suchov** [comment]
#51 will fix this issue too, closing this one
