### ISSUE TITLE
Layout for course description breaks at some width

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#24]
When at ~760px width, when you hover over course checkbox it's description would be overlapped by form.

**Comment by sudodoki** [comment]
>I hidden description for mid width devices.

Idea was to show those all the time instead. :sob:

**Comment by mayosh** [comment]
Don't cry! Just answer: Where do you want me to put them?

**Comment by sudodoki** [comment]
Could not reproduce
