### ISSUE TITLE
update coach info

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#33]
Time passes. Extra year(s) of experience are here.

**Comment by suchov** [comment]
I see only @denyago has years of experiance - what we need to change - right?

**Comment by sudodoki** [comment]
As far as I can tell - Sergey, Denis, Julia

**Comment by programulya** [comment]
We could write just since 1900 year (for example), it will be more flexible for future support :smiley:

**Comment by sudodoki** [comment]
Not an issue as bio was removed.
