### ISSUE TITLE
Submit form issue.

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#40]
>Обратной формы связи не нашел на сайте, посему сюда пишу.
Пожелание: клирьте форму или блокируйте submit кнопку если риквест ушел, а то статус не совсем понятен, риспонс приходит долго и за все время можно нариквестить +100500 заявок.

**Comment by suchov** [comment]
по этому поводу https://www.linkedin.com/in/isabelleseale предложила сделать секцию о прошедших курсах - как это было коротко, и будующих курсах/частоте их проведения

**Comment by suchov** [comment]
@sudodoki in #49 we'll worki on this issue, closing this one

**Comment by sudodoki** [comment]
@suchov :exclamation: issue was about not being able to understand, whether form was already submitted when registering.

**Comment by suchov** [comment]
Oh, sorry then @sudodoki
