### ISSUE TITLE
add an area that explain about previous courses, and how often we are having them

### ISSUE THREAD

**Issue by suchov** [Kottans/kottans.github.io#49]

**Comment by mayosh** [comment]
I'll take it. Please provide the text.

**Comment by suchov** [comment]
@mayosh @sudodoki I think we can create back-end for it, but for now just text is the main, so:
"Starting from 2012: 5 RoR courses, 2 JavaScript, 1 C#, 1 Erlang course was organized by Kottans. Upcoming JS course will take place in spring in Kiev. Preparations will start in February. Apply to course: http://kottans.org/#contact
Wellcome to our chat: https://gitter.im/Kottans/kottans.github.io"
