### ISSUE TITLE
Add the title that explain - what is the project about

### ISSUE THREAD

**Issue by suchov** [kottans/kottans.github.io#51]

**Comment by mayosh** [comment]
Give me some text please.

**Comment by suchov** [comment]
I can suggest: "Free, community-based offline courses."
@listochkin @sudodoki any ideas? I think it must be like a short slogan.

**Comment by listochkin** [comment]
Seems fine to me.

**Comment by sudodoki** [comment]
Kk to me

**Comment by suchov** [comment]
@mayosh then I think it's done from me ;)
