### ISSUE TITLE
broken link to github

### ISSUE THREAD

**Issue by suchov** [Kottans/kottans.github.io#52]
Link broken to Valentine Radchuk github.
https://github.com/zzaknafeyn
@sudodoki can you help to figure out?

**Comment by suchov** [comment]
actually all .net guys have broken links

**Comment by sudodoki** [comment]
Should be fixed by https://github.com/Kottans/kottans.github.io/pull/53 - feel free to merge

**Comment by suchov** [comment]
thanks @sudodoki you are quick as usually!
