### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by suchov** [Kottans/kottans.github.io#59]
<img width="455" alt="form" src="https://cloud.githubusercontent.com/assets/1478985/13249964/e663c392-da2f-11e5-925b-c6c757fa18a5.png">

**Comment by sudodoki** [comment]
@suchov it's standard input type='email' validation. My resolution - won't fix.

**Comment by firec0der** [comment]
if a user doesn't want to fill in a valid email - it's their problem.

**Comment by suchov** [comment]
It was my first thought too, ok closing it then.
