### ISSUE TITLE
Kyiv coaches - add images

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#74]

**Comment by sudodoki** [comment]
following #73

**Comment by sudodoki** [comment]
Maybe, also image of [Denis Stoyanov](https://twitter.com/xgrommx)

**Comment by suchov** [comment]
pinged yesterday some coaches:
@shvaikalesh @mkozhukharenko @cwayfinder @lavriv92

**Comment by sudodoki** [comment]
this is done in #88
