### ISSUE TITLE
Add Lviv C# coaches

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#79]
For [this one](https://dou.ua/forums/topic/18022/)

**Comment by programulya** [comment]
Coaches were added in https://github.com/Kottans/kottans.github.io/commit/3bab327daac83e526fe4fd9aa08e06c9110796d5 and https://github.com/Kottans/kottans.github.io/commit/8308d1e196ed49176254d3e05a473f9879ce5bcd.
