### ISSUE TITLE
Add ruby coaches from Ruby course of fall 2016

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#89]
Right now I want to slightly change some things, but afterwards we will need to do it for:
+ [x] Kyiv
+ [ ] Kharkiv

**Comment by sudodoki** [comment]
@petrokoriakin / @zxftr45 if you would do that, that would be just great. Given it was 2016 fall, it should be 2016-2017 years in https://github.com/Kottans/kottans.github.io/blob/master/_data/coaches.yml

**Comment by sudodoki** [comment]
Kyiv part done in https://github.com/Kottans/kottans.github.io/pull/90

**Comment by tilast** [comment]
@sudodoki thanks :bow:
