### ISSUE TITLE
Add latest writeup 

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans.github.io#91]
Add https://ain.ua/2017/08/04/kotani-zapustili-novyj-kurs to https://github.com/Kottans/kottans.github.io/blob/master/_data/writeups.yml

**Comment by shvaikalesh** [comment]
Do we really want to include those links? Articles contain literally zero helpful info and 100% tech writer BS. Oh, and the comments.

**Comment by sudodoki** [comment]
Indicating "oh, this isn't dead site" might be useful, imo
